

pre marital:
    Oblique : age dependant (older 
    Horizontal :  age band 
post marital:
    Oblique : just mother/father in law =>  need 
    Horizontal :  age band 



Fission, when reach T we remove the agent that fission.


```{r}
etopo <- read.csv(textConnection(
"altitudes,colours
10000,#FBFBFB
4000,#864747
3900,#7E4B11
2000,#9B8411
1900,#BD8D15
300,#F0CF9F
0,#307424
-1,#AFDCF4
-12000,#090B6A
"
), stringsAsFactors=FALSE)
etopo$altitudes01 <- scales::rescale(etopo$altitudes)


etopo.colors <- function(n) {
  colorRampPalette(etopo$colours)(n)
  }

source("R/population.R")
N=100
Th=400
z=4 #number of neutral traits
ki <- 5
km <- 2
K  <-  ki+km
m=.2 #proba marriage
b=.1 #HG birth rate
r=.2 #farmer scale param
rho=.5 #marriage rule
d=0.01

a=initAdaptiveTraits(ki=ki,km=km)
neutraltraitsParam=initNeutralTraits(z = z)
neutraltraitsParam$s=c(0,0,1,1)

reproduction <- function(p1,p2,tp,i=NULL){
    stopifnot(p1$community==p2$community)
    traits=ifelse(sample(c(0,1),length(tp$s),replace=T),p1$traits,p2$traits)
    if(!is.null(i))id=as.numeric(i)+1
    list(
         id=as.character(id),
         traits=traits,
         age=0,
         community=p1$community,
         sex=sample(c("F","M"),1),
         repro=FALSE,
         partner=-1
    )
}

ip=1:N
names(ip)=ip
population=lapply(ip,function(i)
                      list(
                           id=as.character(i),
                           traits=sample(c(0,1),size=z,replace=T),
                           age=sample.int(80,1),
                           community=sample.int(K,1),
                           sex=sample(c("F","M"),1),
                           repro=FALSE,
                           partner=-1
                      )
)

pos=random2Dgrid(K=K,Gx=100)
initcomus=initialiseCommunities(traits=a,coordinates=pos)
size=table(sapply(population,"[[","community"))
initcomus$size=size
plot(initcomus$coordinates,pch=21,bg=apply(initcomus$adaptivetraits,1,mean)+1,cex=log(initcomus$size))
logging="time"
tstep=1000
popsize=c()
popsum=list()
for(time in 1:tstep){
    if(logging=="time")print(paste("------",time,"------"))
    for(i in sample(1:length(population))){
        ind=tryCatch(population[[i]]$id,error=function(e)NULL)
        if(!is.null(ind)){
            ##ageing

            population[[ind]]$age=population[[ind]]$age+1

            ##repro
            partner=population[[ind]]$partner
            canrepro=population[[ind]]$repro
            if(partner>0 & !canrepro){
                if(logging=="verbose")print(paste("childtest",ind,partner,population[[ind]]$community,population[[partner]]$community))
                population[[partner]]$repro=TRUE #make sure proba of reproduction is unique for all pair 
                ad_tr=initcomus$adaptivetraits[population[[ind]]$community,]
                lambda=b+r*sum(ad_tr)
                nchild=rpois(1,lambda)
                if(nchild>0){
                    for(i in 1:nchild){
                        newborn=reproduction(population[[ind]],population[[partner]],neutraltraitsParam,population[[length(population)]]$id)
                        if(logging=="demo")print(paste("newborn in ",newborn$community))
                        population[[newborn$id]]=newborn
                        initcomus$size[newborn$community]=initcomus$size[newborn$community]+1
                    }
                }
            }
            population[[ind]]$repro=FALSE

            ##marriage
            if(population[[ind]]$age>18 & population[[ind]]$partner <0){
                #print("marriage attempt")
                if(runif(1)<m){
                    potential=sapply(population,function(i,s)if(i$age>18 & i$partner<0 & i$sex != s )return(i$id),s=population[[ind]]$sex)
                    potential=unlist(potential)
                    if(length(potential)>0){
                        if(length(potential)==1)partner=potential
                        else partner=sample(potential,1)
                        population[[ind]]$partner=partner
                        population[[partner]]$partner=ind

                        if( population[[ind]]$sex == "F"){
                            fc=population[[ind]]$community
                            mc=population[[partner]]$community
                            stopifnot(population[[partner]]$sex=="M") #temp test
                        }
                        else{
                            mc=population[[ind]]$community
                            fc=population[[partner]]$community
                            stopifnot(population[[partner]]$sex=="F")

                        }
                        ## choice of new community  // ugly ; could do a function(rho,fc,mc) return(lc,jc) & ifelse
                        if(runif(1)<rho){
                            lc=fc #leaving the father's community
                            jc=mc #joining the mother's community
                        }
                        else{
                            jc=fc #joining the father's community
                            lc=mc #leaving the mother's community
                        }

                        initcomus$size[jc]=initcomus$size[jc]+1
                        initcomus$size[lc]=initcomus$size[lc]-1
                        population[[ind]]$community=population[[partner]]$community=jc

                        if(logging=="pairing")print(paste("marriage",ind,partner,"moving all to",jc," and leaving",lc, ",new:" ,population[[partner]]$community,population[[ind]]$community))
                    }
                }
            }

            #Handle deaths
            if(runif(1)<d){
                if(partner>0) population[[partner]]$partner=-1
                initcomus$size[population[[ind]]$community]=initcomus$size[population[[ind]]$community]-1
                if(logging=="demo") print(paste("dead ind",ind,"in",population[[ind]]$community))
                population[[ind]]=NULL
            }
        }


        ##pm transmission

    }

    ## Fission
    overloaded=initcomus$size>Th
    if(sum(overloaded)>0){
        for(split in which(overloaded))
            print(paste("community",split,"with size",initcomus$size[split]))
        #        for(split in which(overloaded))

    }


    #quick summary of population at time 
    popsum[[time]]=sapply(names(population[[1]]),function(n)table(sapply(population,"[[",n)))

    ##
    plot(initcomus$coordinates,pch=21,bg=apply(initcomus$adaptivetraits,1,mean)+1,cex=log(initcomus$size))
    popsize=c(popsize,length(population))

    stopifnot(any(initcomus$size==table(sapply(population,"[[","community"))))
}

plot(popsize)


sumcomu=sapply(popsum,"[[","community")
plot(1,1,ylim=range(0,sumcomu),xlim=c(0,ncol(sumcomu)),type="n")
lapply(1:K,function(k) lines(sumcomu[k,],col=mean(initcomus$adaptivetraits[k,])+1,lwd=2) )



