```{r}
devtools::load_all(".")

N=300
Th=400 #fission threshold
ki <- 2
km <- 1
K  <-  ki+km
m=1 #proba marriage
b=.2 #HG birth rate
r=.05 #farmer scale param
rho=.5 #marriage rule
d=0.001
maturity=0
endrepro=20

a=initAdaptiveTraits(ki=ki,km=km)
z=4 #number of neutral traits
neutraltraitsParam=initNeutralTraits(z = z)
neutraltraitsParam$s=c(0,0,1,1)

ip=1:N
names(ip)=ip
population=lapply(ip,function(i) list( id=as.character(i), traits=sample(c(0,1),size=z,replace=T), age=sample.int(endrepro-5,1), community=sample.int(K,1), sex=sample(c("F","M"),1), repro=FALSE, partner=-1))

pos=random2Dgrid(K=K,Gx=100)
initcomus=initialiseCommunities(traits=a,coordinates=pos)
size=table(sapply(population,"[[","community"))
initcomus$size=size
plot(initcomus$coordinates,pch=21,bg=apply(initcomus$adaptivetraits,1,mean)+1,cex=log(initcomus$size))


tstep=200

quick=modelOOstyle( K =K, m=m, b=b, r=r, rho=rho, d=d, maturity=maturity, endrepro=endrepro, population=population, initcomus=initcomus, tstep=tstep, neutraltraitsParam=neutraltraitsParam, logging=c("na"),ma=endrepro-maturity)


plot(quick$popsize)

tstep=50
maturity=18
endrepro=60
m=.2
quick=modelOOstyle( K =K, m=m, b=b, r=r, rho=rho, d=d, maturity=maturity, endrepro=endrepro, population=population, initcomus=initcomus, tstep=tstep, neutraltraitsParam=neutraltraitsParam, logging=c("na"),ma=1)
plot(quick$popsize)
sumcomu=sapply(quick$popsum,"[[","community")
plot(1:tstep,ylim=range(sumcomu),type="n",ylab="pop size",,xlab="time")
lapply(1:K,function(k) lines(sumcomu[k,],col=mean(initcomus$adaptivetraits[k,])+1,lwd=3) )
```

Having only one community with only one kind of traits (all 0 or all 1), maturity and compare to
$$ N_t=N_{t-1}+\Sigma(poiss(b+r \times a,N_{t-1}))-N_{(t-1)} \times d $$ with a=0 for I, 1 for M

```{r}
library(parallel)
m=1
b=0.2
r=0.05
tstep=300
d=0.001
N=200
ip=1:N
names(ip)=ip
z=4 #number of neutral traits
neutraltraitsParam=initNeutralTraits(z = z)
neutraltraitsParam$s=c(0,0,1,1)
population=lapply(ip,function(i) list( id=as.character(i), traits=sample(c(0,1),size=z,replace=T), age=sample.int(65,1), community=1, sex=sample(c("F","M"),1), repro=FALSE, partner=-1))

pos=random2Dgrid(K=1,Gx=100)

tstep=30
for(mature_adjust in c(1,60)){

    cl=makeCluster(10,"FORK")
    tentriesOnlyF=parLapply(cl,1:10,function(i){set.seed(as.numeric(Sys.time())+i);modelOOstyle(m=m, b=b, r=r,  d=d, maturity=0, endrepro=10000, logging="time", population=population, initcomus=initialiseCommunities(traits=initAdaptiveTraits(ki=0,km=1),coordinates=pos) , tstep=tstep, neutraltraitsParam=neutraltraitsParam,ma=mature_adjust)})

    tentriesOnlyHG=parLapply(cl,1:10,function(i){set.seed(as.numeric(Sys.time())+i);modelOOstyle(m=m, b=b, r=r,  d=d, maturity=0, endrepro=10000, logging="time", population=population, initcomus=initialiseCommunities(traits=initAdaptiveTraits(ki=1,km=0),coordinates=pos) , tstep=tstep, neutraltraitsParam=neutraltraitsParam,ma=mature_adjust)})

    stopCluster(cl)

    xyr=range(sapply(tentriesOnlyF,"[[","popsize"), sapply(tentriesOnlyHG,"[[","popsize"))
    plot(1:tstep,ylim=xyr,type="n",log="y",ylab="pop size",,xlab="time")
    lapply(tentriesOnlyF,function(res) lines(res$popsize,col=2,lwd=3) )
    lapply(tentriesOnlyHG,function(res) lines(res$popsize,col=1,lwd=3) )



    ## Demographic model only
    for(i in 1:100){
        hg=vector("numeric",tstep/mature_adjust)
        fa=vector("numeric",tstep/mature_adjust)
        fa[1]=N
        hg[1]=N

        for(i in 2:max(3,tstep/mature_adjust)){
            hg[i]=hg[i-1]+sum(rpois(hg[i-1],b+r*sum(c(0,0,0))))-hg[i-1]*d
            fa[i]=fa[i-1]+sum(rpois(fa[i-1],b+r*sum(c(1,1,1))))-fa[i-1]*d
        }
        #plot(1,1,type="n",ylim=range(hg,fa),xlim=c(0,dur))
        lines(c(1,2:(length(fa))*(mature_adjust)),fa,col=2,lty=2,lwd=1)
        lines(c(1,2:(length(hg))*(mature_adjust)),hg,col=1,lty=2,lwd=1)
    }
    legend("bottomright",legend=c(expression(N[t]==N[t-1]+Sigma(poiss(b,N[t-1]))-N[t-1]*d),expression(N[t]==N[t-1]+Sigma(poiss(b+r,N[t-1]))-N[t-1]*d),"model 1 community HG","model 1 communit F"),lty=c(2,2,1,1),col=c(1,2,1,2),cex=.8)
}


```
