```{r}
devtools::load_all(".")

N=400
ki <- 1
km <- 1
K  <-  ki+km
z=5

neutraltraitsParam=initNeutralTraitsPathways(z = z)
neutraltraitsParam$s=c(0,0,1,1)
neutraltraitsParam$pre[,"v"]=c(1,1,1,0,0)

pos=random2Dgrid(K=K,Gx=100)
a=initAdaptiveTraits(ki=ki,km=km)
initcomus=initialiseCommunities(traits=a,coordinates=pos)
initcomus$size=rep(round(N/K),K)

migrantsprovenances=matrix(0,nrow=length(initcomus$size),ncol=length(initcomus$size))

communities=unlist(lapply(1:K,function(i)rep(i,initcomus$size[i])))
population=cbind(newpop(N,age="random",community = communities),initNeutralTraits(N,z))
quickV=modelVector(m=1, b=0.03*6, r=0, rho=.5, d=0.03, maturity=18, endrepro=65, population=population, comus=initcomus, tstep=200, tp=neutraltraitsParam, logging=c("time","visu","fission","marriage"),ma=1,traitsid=paste0("t",1:z),out=c("popsumary","finalpop","popsize","weddings"),F_Th=800)

```


Testing just adaptive learning:

```{r}
beta=0

N=100
adaptivetraits=initAdaptiveTraits(2,2)

#community 1 and 2 don't have adaptive traits but 3 and 4 yes

migrants = c(0,0,25,25)
#likelyhood of community on t switch knowing that 20 migrants are comming from 2, 40 from 3 and 50 from for:
betas=seq(0,1,length.out=100)
Pi=sapply(betas,function(beta) probaAdoptionAdaptiveTraits(beta=beta,migrants=migrants,N=N+50,adaptivetraits=adaptivetraits)[1])
plot(betas,Pi)
plot(0,1,ylim=c(0,1),xlim=c(0,1),xlab=expression(beta),ylab="proba adoption")
for(permi in seq(0,.1,length.out=10)){
    migrants = c(0,0,permi*N,permi*N)
    #likelyhood of community on t switch knowing that 20 migrants are comming from 2, 40 from 3 and 50 from for:
    betas=seq(0,1,length.out=100)
    Pi=sapply(betas,function(beta) probaAdoptionAdaptiveTraits(beta=beta,migrants=migrants,N=N+2*permi*N,adaptivetraits=adaptivetraits)[1])
    points(betas,Pi)
}

migrants = c(0,0,25,25)
#likelyhood of community on t switch knowing that 20 migrants are comming from 2, 40 from 3 and 50 from for:
betas=seq(-10,10,length.out=100)
Pi=sapply(betas,function(beta) probaAdoptionAdaptiveTraits(beta=beta,migrants=migrants,N=N+50,adaptivetraits=adaptivetraits)[1])
plot(betas,Pi)
plot(0,1,ylim=c(0,1),xlim=c(0,10),xlab=expression(beta),ylab="proba adoption")
for(permi in seq(0,.1,length.out=10)){
    migrants = c(0,0,permi*N,permi*N)
    #likelyhood of community on t switch knowing that 20 migrants are comming from 2, 40 from 3 and 50 from for:
    betas=seq(0,1,length.out=100)
    Pi=sapply(betas,function(beta) probaAdoptionAdaptiveTraits(beta=beta,migrants=migrants,N=N+2*permi*N,adaptivetraits=adaptivetraits)[1])
    points(betas,Pi)
}

migrants = c(0,50,0,0)
#likelyhood of community on t switch knowing that 20 migrants are comming from 2, 40 from 3 and 50 from for:
betas=seq(-10,10,length.out=100)
Pi=sapply(betas,function(beta) probaAdoptionAdaptiveTraits(beta=beta,migrants=migrants,N=N+50,adaptivetraits=adaptivetraits))
plot(betas,Pi[1,])
plot(0,1,ylim=c(0,1),xlim=c(0,10),xlab=expression(beta),ylab="proba adoption")
for(permi in seq(0,.1,length.out=10)){
    migrants = c(0,0,permi*N,permi*N)
    #likelyhood of community on t switch knowing that 20 migrants are comming from 2, 40 from 3 and 50 from for:
    betas=seq(0,1,length.out=100)
    Pi=sapply(betas,function(beta) probaAdoptionAdaptiveTraits(beta=beta,migrants=migrants,N=N+2*permi*N,adaptivetraits=adaptivetraits)[1])
    points(betas,Pi)
}
```



```{r}
beta=0

N=100
adaptivetraits=initAdaptiveTraits(2,2)

migrants1 = c(0,0,25,25)
updateTraits(
k=1
,
k.size=N+sum(migrants1[-1])
,
alltraits=adaptivetraits
,
migrantscount=migrants1
)
migrants2 = c(25,25,0,0)

#if beta=1 no matter the number of migrants when the are > 0 the likelilihood of k adopting a should tends to 0.5
apply(replicate(1000, updateTraits(k=1,k.size=150,alltraits=adaptivetraits,migrantscount=sample(100,4,replace=T),beta=1)),1,sum)/1000

#if beta=0 the probability to adopt a traits i k/N, thus if N=100 and we have 2 and 2 this should be 4/100 
apply(replicate(1000, updateTraits(k=1,k.size=100,alltraits=adaptivetraits,migrantscount=c(0,0,2,2),beta=0)),1,sum)/1000

#Not this implementation allow to also do the same from 1 to 0
apply(replicate(1000, updateTraits(k=3,k.size=100,alltraits=adaptivetraits,migrantscount=c(2,2,0,0),beta=0)),1,sum)/1000
```
