

pre marital:
    Oblique : age dependant (older 
    Horizontal :  age band 
post marital:
    Oblique : just mother/father in law =>  need 
    Horizontal :  age band 



Fission, when reach T we remove the agent that fission.


```{r}
etopo <- read.csv(textConnection(
"altitudes,colours
10000,#FBFBFB
4000,#864747
3900,#7E4B11
2000,#9B8411
1900,#BD8D15
300,#F0CF9F
0,#307424
-1,#AFDCF4
-12000,#090B6A
"
), stringsAsFactors=FALSE)
etopo$altitudes01 <- scales::rescale(etopo$altitudes)


etopo.colors <- function(n) {
  colorRampPalette(etopo$colours)(n)
  }

devtools::load_all(".")
N=200
Th=400 #fission threshold
ki <- 1
km <- 1
K  <-  ki+km
m=1 #proba marriage
b=.2 #HG birth rate
r=.05 #farmer scale param
rho=.5 #marriage rule
d=0.001
maturity=0
endrepro=20
tstep=20*10

a=initAdaptiveTraits(ki=ki,km=km)
z=4 #number of neutral traits
neutraltraitsParam=generatePathways(z = z)
neutraltraitsParam$s=c(0,0,1,1)

ip=1:N
names(ip)=ip
population=lapply(ip,function(i)
                      list(
                           id=as.character(i),
                           traits=sample(c(0,1),size=z,replace=T),
                           age=sample.int(80,1),
                           community=sample.int(K,1),
                           sex=sample(c("F","M"),1),
                           repro=FALSE,
                           partner=-1
                      )
)

pos=random2Dgrid(K=K,Gx=100)
initcomus=initialiseCommunities(traits=a,coordinates=pos)
size=table(sapply(population,"[[","community"))
initcomus$size=size
plot(initcomus$coordinates,pch=21,bg=apply(initcomus$adaptivetraits,1,mean)+1,cex=log(initcomus$size))


tentries=replicate(10,modelOOstyle( N=N, Th=Th, K =K, m=m, b=b, r=r, rho=rho, d=d, maturity=maturity, endrepro=endrepro, logging="time", population=population,comus=initcomus, tstep=tstep, neutraltraitsParam=neutraltraitsParam))

plot(1:200,ylim=c(0,600),type="n")
popsums=apply(tentries,2,function(res){
                   popsum=res$popsum
                   sumcomu=sapply(popsum,"[[","community")
                   lapply(1:K,function(k) lines(sumcomu[k,],col=mean(initcomus$adaptivetraits[k,])+1,lwd=2) )
})

lines(1:length(fa)*(endrepro-maturity),fa,col="red",lty=2,lwd=2)
lines(1:length(hg)*(endrepro-maturity),hg,col="black",lty=3,lwd=2)


moveA <- function(listmove,pop,newcom){
            for( m in listmove){
                pop[[m]]$community = newcom
            }
}

moveB <- function(listmove,pop,newcom){
    pop[moving]=lapply(pop[moving],function(m,nc){m$commnunity=nc;m},nc=newcom)
}

library(microbenchmark)
microbenchmark(moveA(moving,population,2),moveB(moving,population,2))


#keep horizontal: +/- 10 years  oblique 

#when list (remove and fission)
plot(1,1,ylim=range(0,sumcomu),xlim=c(0,max(lengths(sumcomu))),type="n")
lapply(1:K,function(k) lines(sumcomu[[k]]),col=mean(initcomus$adaptivetraits[k,])+1,lwd=2) )
