

#using a the result of a simulation
#return the type of comu (0,1,2,3) 
getCommuType <- function(exp){
    comusize=exp$comusize
    ncomu=length(comusize[[length(comusize)]])
    sapply(1:ncomu,function(com){
               st=min(which(!is.na(sapply(comusize,function(size)size[com]))))
               sum(exp$traitpercomu[[st]][com,paste0("a",1:3)]/comusize[[st]][com])
    })
}

#using a the result of a simulation
#return the type of comu (0,1,2,3) 
getCountBySex <- function(population,pathways,type=NULL){
    traitsid=paste0("t",seq_along(pathways$s))
    freqcom=c()
    for(s in c(0,1)){
        single.bias=traitsid[pathways$s == s]
        singlesex=population[population[,"sex"]==s,]
        applysinglesex[,single.bias] 
~ singlesex.comus
    }       
    single.bias=traitsid[pathways$s == 0.5]
    freqcom=cbind(freqcom,xtabs(population[,single.bias] ~ population[,"community"])/as.numeric(table(population[,"community"])))
    freqcom[,traitsid]
}

#using a the result of a simulation
#return the type of comu (0,1,2,3) 
getCountBySexAndCommu <- function(population,pathways,type=NULL){
    traitsid=paste0("t",seq_along(pathways$s))
    freqcom=c()
    wholecomus=sort(unique(population[,"community"])) 
    for(s in c(0,1)){
        single.bias=traitsid[pathways$s == s]
        singlesex=population[population[,"sex"]==s,]
        singlesex.comus=factor(singlesex[,"community"],levels=wholecomus)
        freqcom=cbind(freqcom,xtabs(singlesex[,single.bias] ~ singlesex.comus)/as.numeric(table(singlesex.comus)))
    }       
    single.bias=traitsid[pathways$s == 0.5]
    freqcom=cbind(freqcom,xtabs(population[,single.bias] ~ population[,"community"])/as.numeric(table(population[,"community"])))
    freqcom[,traitsid]
}

#diffexp allo to keep separated simulation within the same folder but that have been generated by different parameters
extractResults <- function(expname,pathways=pathways,traitsel=NULL,type=F,diffexp=F){
    allsingle.exp <- list.files(expname,pattern = "si.*\\.RDS",full.names = TRUE)
    alltraitComu=lapply(allsingle.exp,function(expfname){
                            print(expfname)
                            one=readRDS(expfname)
                            population=NULL
							end=getSimFull(one)
                            if(is.null(one$popwhenfull))
                                population=one$population
                            else
                                population=one$popwhenfull
							if(type){
								ctypes=apply(one$traitpercomu[[end]][,paste0("a",1:3)]/one$comusize[[end]],1,sum)
								ctypes=ctypes[!is.nan(ctypes)]
								ctypes[ctypes %in% c(1,2)]=-1
								ctypes[ctypes==0]=1
								ctypes[ctypes==3]=2
								ctypes[ctypes==-1]=3
								ctypes=factor(ctypes,levels=c(1,2,3))
								counts=getCountBySexAndCommu(population,pathways)
								lapply(levels(ctypes),function(ct)counts[ctypes==ct,,drop=F])
							}
							else
								getCountBySexAndCommu(population,pathways)
    })
    if(type)lapply(1:3,function(ctype)lapply(traitsel,function(ti)unlist(lapply(alltraitComu,function(singex)if(nrow(singex[[ctype]])>0)singex[[ctype]][,ti]))))
    else if(!diffexp) lapply(traitsel,function(ti) unlist(lapply(alltraitComu,function(singex)singex[,ti])))
}


getDensities <- function(traits,bw=0.05){
    if(is.null(traits))return(NULL)
    traits.dens=density(traits,na.rm=T,from=0,to=1,bw=bw)
    y=c(0,traits.dens$y,0)
    x=c(0,traits.dens$x,1)
    return(cbind(x,y/max(y)))
}

getSimFull <- function(simres){
    if(any(lengths(simres$comusize)==100))
        min(which(lengths(simres$comusize)==100))
    else
        length(simres$popsize)
}

